version: "3.2"

services:
  local:
    build: .
    image: go-package-template
    volumes:
      - ./:/go/src

  test:
    build: .
    image: go-package-template
    entrypoint: go test -v ./github.com/mm0202-sandbox/template_go-package/
    volumes:
      - ./:/go/src
      
  bundle:
    build: .
    image: go-package-template

  bundle-test:
    build: .
    image: go-package-template
    entrypoint: go test -v ./github.com/mm0202-sandbox/template_go-package/
